#!/bin/sh
#
# Special thanks to zipleen for the original Tomato/DD-WRT script that this 
# one is based on:
#
# https://github.com/zipleen/tomato-ddwrt-meo-iptv-scripts/blob/master/dhcpevent.sh
# 
# ----
#
# This script is run by the udhcpc program (via the wan-start script).
#
# The following variables are passed into it (w/example values):
#
# $interface: vlan12
# $vlan_ip: 10.x.x.x
# $subnet: 255.255.192.0
# $vlan_gateway: 10.y.y.y
#
# Its purpose is to set up the routes so that requests to MEO specific services
# from the private local network are routed to the MEO IPTV/VoIP vlan.

vlan_iface=$interface
vlan_ip=$ip
vlan_subnet=$subnet
vlan_gateway=$router
vlan_ssn=`echo "$vlan_gateway"| sed -e "s/.1$/.0/g"| awk '{print $0"/20"}'`


# duped from _net_config
vlan_ip_file="/tmp/vlan_ip"

source /jffs/scripts/custom/_net_functions
init_config

#-----------------------------------------------------------------------------
# These routes are set up on the original hardware, as observed in a backup 
# file (user.ini).
#-----------------------------------------------------------------------------
configure_meo_routes () {
  logger "$0: setting up IPTV VLAN routes"
  
  #route add -net 10.173.0.0 netmask 255.255.0.0 gw $vlan_gateway dev $vlan_iface
  
  #default subnet route
  ip route add $vlan_ssn  via $vlan_gateway dev $vlan_iface     
  for tgts in $IPTV_NETS;do
  	logger "$0:        ip route add $tgts via $vlan_gateway dev $vlan_iface "
  	ip route add $tgts via $vlan_gateway dev $vlan_iface
  done
  
  iptables -I INPUT 1 -i $vlan_iface -p udp --dst 224.0.0.0/4 -j ACCEPT
  iptables -I FORWARD -i $vlan_iface -o br0 -s $vlan_ssn -j ACCEPT
                           
  iptables --table nat -I POSTROUTING 1 --source $LAN_NET --destination $vlan_ssn --out-interface $vlan_iface --jump SNAT --to-source $vlan_ip
  logger "$0: saving vlan ip $vlan_ip to $vlan_ip_file"
  
  # Now that we have the routes set up, we need to set up some firweall rules:
  echo $vlan_ip > $vlan_ip_file
}

#-----------------------------------------------------------------------------
deconfig() {
  ifconfig $vlan_iface 0.0.0.0
}
 
#-----------------------------------------------------------------------------
bound() {

  # debug environment variables
  #env > /tmp/env
    
  logger "$0: bound event variables: ip: $vlan_ip, iface: $vlan_iface, router: $vlan_gateway"

  # define interface IP
  ifconfig $vlan_iface $vlan_ip netmask $vlan_subnet
  
  # rp_filter must be off on vlan12!!!
  echo 0 > /proc/sys/net/ipv4/conf/$vlan_iface/rp_filter
        
  configure_meo_routes
 
  logger "$0: completed"
}

#-----------------------------------------------------------------------------
renew() {
  # I'm lazy so I'm just goin to run all the commands again! Seems to work :P 
  bound
}
    
case $1 in
  deconfig)
    deconfig
  ;;
  bound)
    bound
  ;;
  renew)
    renew
  ;;
  update)
    renew
  ;;
esac
